SINGLE_CONSONANTS = [
    "k",
    "kh",
    "g",
    "gh",
    "ṅ",
    "c",
    "ch",
    "j",
    "jh",
    "ñ",
    "ṭ",
    "ṭh",
    "ḍ",
    "ḍh",
    "ṇ",
    "t",
    "th",
    "d",
    "dh",
    "n",
    "p",
    "ph",
    "b",
    "bh",
    "m",
    "y",
    "r",
    "l",
    "v",
    "ś",
    "ṣ",
    "s",
    "h",
]

from itertools import product

CONSONANT_CLUSTERS = list(SINGLE_CONSONANTS) + [
    c1 + c2 for c1, c2 in product(SINGLE_CONSONANTS, repeat=2) if c1 != c2
]

VOWELS = ["a", "ā", "i", "ī", "u", "ū", "ṛ", "ṝ", "ḷ", "ḹ", "e", "ai", "o", "au"]
FINALS = ["ṁ", "ḥ", "m", "ṭ", "t", ""]  # traditional finals


CONSONANT_METADATA = {
    "k": {
        "Place": "velar",
        "Manner": "stop",
        "Voicing": "voiceless",
        "Aspiration": "no",
        "Nasal": "no",
        "Sibilant": "no",
        "Retroflex": "no",
    },
    "kh": {
        "Place": "velar",
        "Manner": "stop",
        "Voicing": "voiceless",
        "Aspiration": "yes",
        "Nasal": "no",
        "Sibilant": "no",
        "Retroflex": "no",
    },
    "g": {
        "Place": "velar",
        "Manner": "stop",
        "Voicing": "voiced",
        "Aspiration": "no",
        "Nasal": "no",
        "Sibilant": "no",
        "Retroflex": "no",
    },
    "gh": {
        "Place": "velar",
        "Manner": "stop",
        "Voicing": "voiced",
        "Aspiration": "yes",
        "Nasal": "no",
        "Sibilant": "no",
        "Retroflex": "no",
    },
    "ṅ": {
        "Place": "velar",
        "Manner": "nasal",
        "Voicing": "voiced",
        "Aspiration": "no",
        "Nasal": "yes",
        "Sibilant": "no",
        "Retroflex": "no",
    },
    "c": {
        "Place": "palatal",
        "Manner": "affricate",
        "Voicing": "voiceless",
        "Aspiration": "no",
        "Nasal": "no",
        "Sibilant": "yes",
        "Retroflex": "no",
    },
    "ch": {
        "Place": "palatal",
        "Manner": "affricate",
        "Voicing": "voiceless",
        "Aspiration": "yes",
        "Nasal": "no",
        "Sibilant": "yes",
        "Retroflex": "no",
    },
    "j": {
        "Place": "palatal",
        "Manner": "affricate",
        "Voicing": "voiced",
        "Aspiration": "no",
        "Nasal": "no",
        "Sibilant": "yes",
        "Retroflex": "no",
    },
    "jh": {
        "Place": "palatal",
        "Manner": "affricate",
        "Voicing": "voiced",
        "Aspiration": "yes",
        "Nasal": "no",
        "Sibilant": "yes",
        "Retroflex": "no",
    },
    "ñ": {
        "Place": "palatal",
        "Manner": "nasal",
        "Voicing": "voiced",
        "Aspiration": "no",
        "Nasal": "yes",
        "Sibilant": "no",
        "Retroflex": "no",
    },
    "ṭ": {
        "Place": "retroflex",
        "Manner": "stop",
        "Voicing": "voiceless",
        "Aspiration": "no",
        "Nasal": "no",
        "Sibilant": "no",
        "Retroflex": "yes",
    },
    "ṭh": {
        "Place": "retroflex",
        "Manner": "stop",
        "Voicing": "voiceless",
        "Aspiration": "yes",
        "Nasal": "no",
        "Sibilant": "no",
        "Retroflex": "yes",
    },
    "ḍ": {
        "Place": "retroflex",
        "Manner": "stop",
        "Voicing": "voiced",
        "Aspiration": "no",
        "Nasal": "no",
        "Sibilant": "no",
        "Retroflex": "yes",
    },
    "ḍh": {
        "Place": "retroflex",
        "Manner": "stop",
        "Voicing": "voiced",
        "Aspiration": "yes",
        "Nasal": "no",
        "Sibilant": "no",
        "Retroflex": "yes",
    },
    "ṇ": {
        "Place": "retroflex",
        "Manner": "nasal",
        "Voicing": "voiced",
        "Aspiration": "no",
        "Nasal": "yes",
        "Sibilant": "no",
        "Retroflex": "yes",
    },
    "t": {
        "Place": "dental",
        "Manner": "stop",
        "Voicing": "voiceless",
        "Aspiration": "no",
        "Nasal": "no",
        "Sibilant": "no",
        "Retroflex": "no",
    },
    "th": {
        "Place": "dental",
        "Manner": "stop",
        "Voicing": "voiceless",
        "Aspiration": "yes",
        "Nasal": "no",
        "Sibilant": "no",
        "Retroflex": "no",
    },
    "d": {
        "Place": "dental",
        "Manner": "stop",
        "Voicing": "voiced",
        "Aspiration": "no",
        "Nasal": "no",
        "Sibilant": "no",
        "Retroflex": "no",
    },
    "dh": {
        "Place": "dental",
        "Manner": "stop",
        "Voicing": "voiced",
        "Aspiration": "yes",
        "Nasal": "no",
        "Sibilant": "no",
        "Retroflex": "no",
    },
    "n": {
        "Place": "dental",
        "Manner": "nasal",
        "Voicing": "voiced",
        "Aspiration": "no",
        "Nasal": "yes",
        "Sibilant": "no",
        "Retroflex": "no",
    },
    "p": {
        "Place": "labial",
        "Manner": "stop",
        "Voicing": "voiceless",
        "Aspiration": "no",
        "Nasal": "no",
        "Sibilant": "no",
        "Retroflex": "no",
    },
    "ph": {
        "Place": "labial",
        "Manner": "stop",
        "Voicing": "voiceless",
        "Aspiration": "yes",
        "Nasal": "no",
        "Sibilant": "no",
        "Retroflex": "no",
    },
    "b": {
        "Place": "labial",
        "Manner": "stop",
        "Voicing": "voiced",
        "Aspiration": "no",
        "Nasal": "no",
        "Sibilant": "no",
        "Retroflex": "no",
    },
    "bh": {
        "Place": "labial",
        "Manner": "stop",
        "Voicing": "voiced",
        "Aspiration": "yes",
        "Nasal": "no",
        "Sibilant": "no",
        "Retroflex": "no",
    },
    "m": {
        "Place": "labial",
        "Manner": "nasal",
        "Voicing": "voiced",
        "Aspiration": "no",
        "Nasal": "yes",
        "Sibilant": "no",
        "Retroflex": "no",
    },
    "y": {
        "Place": "palatal",
        "Manner": "approximant",
        "Voicing": "voiced",
        "Aspiration": "no",
        "Nasal": "no",
        "Sibilant": "no",
        "Retroflex": "no",
    },
    "r": {
        "Place": "retroflex",
        "Manner": "trill",
        "Voicing": "voiced",
        "Aspiration": "no",
        "Nasal": "no",
        "Sibilant": "no",
        "Retroflex": "yes",
    },
    "l": {
        "Place": "dental",
        "Manner": "lateral",
        "Voicing": "voiced",
        "Aspiration": "no",
        "Nasal": "no",
        "Sibilant": "no",
        "Retroflex": "no",
    },
    "v": {
        "Place": "labiodental",
        "Manner": "approximant",
        "Voicing": "voiced",
        "Aspiration": "no",
        "Nasal": "no",
        "Sibilant": "no",
        "Retroflex": "no",
    },
    "ś": {
        "Place": "palatal",
        "Manner": "fricative",
        "Voicing": "voiceless",
        "Aspiration": "no",
        "Nasal": "no",
        "Sibilant": "yes",
        "Retroflex": "no",
    },
    "ṣ": {
        "Place": "retroflex",
        "Manner": "fricative",
        "Voicing": "voiceless",
        "Aspiration": "no",
        "Nasal": "no",
        "Sibilant": "yes",
        "Retroflex": "yes",
    },
    "s": {
        "Place": "dental",
        "Manner": "fricative",
        "Voicing": "voiceless",
        "Aspiration": "no",
        "Nasal": "no",
        "Sibilant": "yes",
        "Retroflex": "no",
    },
    "h": {
        "Place": "glottal",
        "Manner": "fricative",
        "Voicing": "voiced",
        "Aspiration": "yes",
        "Nasal": "no",
        "Sibilant": "yes",
        "Retroflex": "no",
    },
}
